services:
  backend:
    container_name: back-sv-models 
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
    networks:
      - shared-net  # <- Conectado a red compartida

  celery_worker:
    container_name: celery_worker
    build: 
      context: .
      dockerfile: Dockerfile.worker
    command: ["celery", "-A", "app.tasks.celery_worker", "worker", "--loglevel=info", "-Q", "transcriptions", "--concurrency=1", "-P", "solo"]
    depends_on:
      - redis
    networks:
      - shared-net

  redis:
    image: "redis:latest"
    networks:
      - shared-net

networks:
  shared-net:
    name: shared-net
