services:
  backend:
    container_name: back-sv-models 
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
    networks:
      - shared-net  # <- Conectado a red compartida


networks:
  shared-net:
    name: shared-net
